apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cal-helm.fullname" . }}
  labels:
    {{- include "cal-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cal-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cal-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}"
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- toYaml .Values.service.env | nindent 12 }}
          volumeMounts:
            {{- range .Values.service.volumes }}
            - name: {{ .name }}
              mountPath: {{ .path }}
            {{- end }}
      volumes:
        {{- range .Values.service.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
        {{- end }}
