apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cal-helm.fullname" . }}
  labels:
    {{- include "cal-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cal-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cal-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
             env:                                                                                                                                      
              {{- range $key, $value := .Values.secret }}                                                                                             
              - name: {{ $key }}                                                                                                                      
                valueFrom:                                                                                                                            
                  secretKeyRef:                                                                                                                       
                    name: {{ .Values.secretName }}                                                                                                    
                    key: {{ $key }}                                                                                                                   
              {{- end }}  
          volumeMounts:
            {{- range .Values.service.volumes }}
            - name: {{ .name }}
              mountPath: {{ .path }}
            {{- end }}
      volumes:
        {{- range .Values.service.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
        {{- end }}
