apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cal-helm.fullname" . }}
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "cal-helm.fullname" . }}
                port:
                  number: 7777
