{{- range .Values.service.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.pvc.size }}
{{- end }}
