apiVersion: v1
kind: Secret
metadata:
  name: calcom-secrets
type: Opaque
data:
  NEXT_PUBLIC_WEBAPP_URL: {{ .Values.secret.NEXT_PUBLIC_WEBAPP_URL | b64enc | quote }}
  NEXT_PUBLIC_LICENSE_CONSENT: {{ .Values.secret.NEXT_PUBLIC_LICENSE_CONSENT | b64enc | quote }}
  CALCOM_TELEMETRY_DISABLED: {{ .Values.secret.CALCOM_TELEMETRY_DISABLED | b64enc | quote }}
  NEXTAUTH_SECRET: {{ .Values.secret.NEXTAUTH_SECRET | b64enc | quote }}
  CALENDSO_ENCRYPTION_KEY: {{ .Values.secret.CALENDSO_ENCRYPTION_KEY | b64enc | quote }}
  DATABASE_URL: {{ if .Values.externalDatabase.enabled }}{{ .Values.externalDatabase.url | b64enc | quote }}{{ else }}{{ printf           
   "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.postgresUser .Values.postgresql.postgresPassword .Values.namespace        
   .Values.postgresql.postgresDatabase | b64enc | quote }}{{ end }} 